services:
  simulador-do-caos:
    image: fiorindiluiz/simulador-do-caos:v1
    ports:
      - "8080:3000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 5s
      timeout: 5s
      retries: 2
      start_period: 30s
